# Use postgres/example user/password credentials
version: "3.7"

services:

  db:
    container_name: db
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "db"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    depends_on:
     - db
     - logstash
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8070:80"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "pgadmin"

  web:
    container_name: web
    image: io.github.emlagowski/spring-database-metrics
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example_db
      SPRING_DATASOURCE_USERNAME: example_user
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
      - logstash
    ports:
      - 8080:8080
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "web"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - web
      - logstash
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "prometheus"

  grafana:
    image: grafana/grafana:7.3.10
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=jdbranham-diagram-panel"
    depends_on:
      - prometheus
      - logstash
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "grafana"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "kibana"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.1.141:12201"
        tag: "kibana"

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.6.2
    links:
      - elasticsearch
    volumes:
#      - type: bind
#        source: ./logstash/config/logstash.yml
#        target: /usr/share/logstash/config/logstash.yml
#        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
#      - ./logstash/pipeline/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    command: logstash -f /usr/share/logstash/pipeline
    ports:
      - 12201:12201/udp
      - 9600:9600
      - 5044:5044
    depends_on:
      - elasticsearch