# Use postgres/example user/password credentials
version: "3.7"

services:

  db:
    container_name: db
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    depends_on:
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8070:80"

  web:
    container_name: web
    image: io.github.emlagowski/spring-database-metrics
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example_db
      SPRING_DATASOURCE_USERNAME: example_user
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - web
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.3.10
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=jdbranham-diagram-panel"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards