{
 "title": "Proces Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "db_table_size_rows", "legendFormat": "{{processState}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "db_table_size_rows", "legendFormat": "{{processState}}" }
   ]
  },
  {
   "title": "Proces Graph",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "graph LR\n    A[Registered] -- reg --> B\n    B[In progress] -- proc --> H{How?}\n    H -- a --> C[Auto]\n    H -- m --> D[Manual]\n    C -- ac --> E[Closed]\n    D -- mc --> E"
   },
   "targets": [
    {
     "expr": "db_table_size_rows{processState=\"REGISTERED\"}",
     "legendFormat": "A"
    },
    {
     "expr": "db_table_size_rows{processState=\"IN_PROGRESS\"}",
     "legendFormat": "B"
    },
    {
     "expr": "db_table_size_rows{processState=\"AUTO\"}",
     "legendFormat": "C"
    },
    {
     "expr": "db_table_size_rows{processState=\"MANUAL\"}",
     "legendFormat": "D"
    },
    {
     "expr": "db_table_size_rows{processState=\"CLOSED\"}",
     "legendFormat": "E"
    },
    {
     "expr": "rate(process_movement_total{type=\"REGISTERED\",}[1m])",
     "legendFormat": "reg"
    },
    {
     "expr": "rate(process_movement_total{type=\"REGISTERED->IN_PROGRESS\",}[1m])",
     "legendFormat": "proc"
    },
    {
     "expr": "rate(process_movement_total{type=\"IN_PROGRESS->AUTO\",}[1m])",
     "legendFormat": "a"
    },
    {
     "expr": "rate(process_movement_total{type=\"IN_PROGRESS->MANUAL\",}[1m])",
     "legendFormat": "m"
    },
    {
     "expr": "rate(process_movement_total{type=\"AUTO->CLOSED\",}[1m])",
     "legendFormat": "ac"
    },
    {
     "expr": "rate(process_movement_total{type=\"MANUAL->CLOSED\",}[1m])",
     "legendFormat": "mc"
    }
   ]
  },
  {
   "title": "Stage movement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CLOSED",
     "bucketAggs": [
      {
       "$$hashKey": "object:93",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:91", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web AND app_log.msg:\"Moved to state CLOSED\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "IN_PROGRESS",
     "bucketAggs": [
      {
       "$$hashKey": "object:111",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:109", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web AND app_log.msg:\"Moved to state IN_PROGRESS\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "AUTO",
     "bucketAggs": [
      {
       "$$hashKey": "object:129",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:127", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web AND app_log.msg:\"Moved to state AUTO\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "MANUAL",
     "bucketAggs": [
      {
       "$$hashKey": "object:147",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:145", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web AND app_log.msg:\"Moved to state MANUAL\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "CLOSED",
     "bucketAggs": [
      {
       "$$hashKey": "object:165",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:163", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web AND app_log.msg:\"Moved to state CLOSED\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "App logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:463",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:461", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "container_name:web",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}